networks:
  auth-service-network:
    driver: 'bridge'
volumes:
  auth-service-keycloak-data-training:
    driver: 'local'
  auth-service-keycloak-db-data-training:
    driver: 'local'
  auth-service-redis-data-training:
    driver: 'local'
  postgres-data-training:
    driver: 'local'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db_training
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5438:5432"
    volumes:
      - postgres-data-training:/var/lib/postgresql/data